// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgInventoryRepository

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID        uuid.UUID
	Name      string
	Price     pgtype.Numeric
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Quantity  int32
}
