// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgOrderRepository

import (
	order "davideimola.dev/ddd-onion/pkg/order"
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	Status     order.Status
}
